(* Note this pseudo-EBNF elides whitespace handling *)
Sandwich = Filling, MoreFillings, 'on', Bread;

Filling = 'ham'
        | 'cheese'
        | 'mustard';

MoreFillings = 'and', Filling, MoreFillings
             | ; (* nothing, aka epsilon *)

Bread = 'rye'
      | 'wheat';
